### ISSUE TITLE
链接超过1W无法生成文本

### ISSUE THREAD

**Issue by kudoushinichi6671** [smloli/panCheckUrl#1]
检测1W以上链接的时候，检测完窗口会直接消失掉
不会生成文本，希望可以修复这个bug
链接：[https://www.aliyundrive.com/s/oFy6VkUhQ61](url)

**Comment by smloli** [comment]
> 检测1W以上链接的时候，检测完窗口会直接消失掉 不会生成文本，希望可以修复这个bug 链接：[https://www.aliyundrive.com/s/oFy6VkUhQ61](url)

已修复
