### ISSUE TITLE
我又来打扰了

### ISSUE THREAD

**Issue by kudoushinichi6671** [smloli/panCheckUrl#2]
使用过程中发现了两个bug
1、文本识别不出来，直接窗口消失
2、识别链接生成出现其他错误
建议：阿里云盘链接生成文本是否考虑加上链接原来的提取码
最后感谢作者，希望作者能够越做越好
BUG链接:https://www.aliyundrive.com/s/iQSb3JAzvHq

**Comment by smloli** [comment]
> 使用过程中发现了两个错误 1、文本识别不出来，直接图片删除 2、识别链接生成出现其他错误 建议：阿里云盘链接生成文本考虑加上链接原来的提取码最终 感谢作者，希望能够越做人 BUG链接：[https](https://www.aliyundrive.com/s/iQSb3JAzvHq) : //www.aliyundrive.com/s/iQSb3JAzvHq[](https://www.aliyundrive.com/s/iQSb3JAzvHq)

1. 经测试，url4.txt的编码为utff16，你保存成utf8的编码就可以识别了
2. 已修复
3. 已完成保存提取码的功能
