### ISSUE TITLE
有没有考虑夸克有效性检测

### ISSUE THREAD

**Issue by kudoushinichi6671** [smloli/panCheckUrl#3]
有没有考虑夸克有效链接检测，然后检测出来顺便带上链接名称

**Comment by smloli** [comment]
可能过段时间会弄吧

**Comment by kudoushinichi6671** [comment]
您好，我正在工作中，无法亲自回复您的邮件。我将在看到这封信后，及时的答复你，同时也告诉你一个好消息——我收到你的来信了，不用再发邮件给我了。

**Comment by kudoushinichi6671** [comment]
好的，要是去重功能啥的也考虑下就更好了，忘记说了，这个检测有效性的软件好像用不了了……

**Comment by smloli** [comment]
已经修复了闪退的BUG，夸克的过段时间再弄

**Comment by kudoushinichi6671** [comment]
您好，我正在工作中，无法亲自回复您的邮件。我将在看到这封信后，及时的答复你，同时也告诉你一个好消息——我收到你的来信了，不用再发邮件给我了。
