### ISSUE TITLE
我下载的2.08版本，还是会闪退

### ISSUE THREAD

**Issue by ChhR00** [smloli/panCheckUrl#4]
我下载的2.08版本，还是会闪退，双击打开.EXE，直接闪退，无法使用

**Comment by smloli** [comment]
> 我下载的2.08版本，还是会闪退，双击打开.EXE，直接闪退，无法使用

重新下载最新版试试

**Comment by smloli** [comment]
> 

你的这个闪退，应该是运行目录下没有url.txt这个文件，现在已经更新了延时提示
