### ISSUE TITLE
这是新特性还是bug?win版本

### ISSUE THREAD

**Issue by yunskyline** [smloli/panCheckUrl#7]
好像最新版不再导出名件名，并且有的链接是有效的也会判定为无效链接

**Comment by smloli** [comment]
> 好像最新版不再导出名件名，并且有的链接是有效的也会判定为无效链接

可以发一份测试时的链接吗

**Comment by yunskyline** [comment]
> > 好像最新版不再导出名件名，并且有的链接是有效的也会判定为无效链接
> 
> 可以发一份测试时的链接吗

作者竟然还维护啊！有点小意外。我再测测百度的https://www.aliyundrive.com/s/bwhHcDJ4xpQ
https://www.aliyundrive.com/s/aK8b4rFPuVi
https://www.aliyundrive.com/s/gKT6MDE4fv1
https://www.aliyundrive.com/s/wRscEFhYTyv
https://www.aliyundrive.com/s/2VszP64VL6q
https://www.aliyundrive.com/s/5Q1WzBUaAKb
https://www.aliyundrive.com/s/sqEnbkR41qB
https://www.aliyundrive.com/s/EhwyeYXouk6
https://www.aliyundrive.com/s/BDSEnik5Efr
https://www.aliyundrive.com/s/bWoQqgCDDEZ
https://www.aliyundrive.com/s/ywQR3hvgh9e
https://www.aliyundrive.com/s/vK9eJMjRszu
https://www.aliyundrive.com/s/vmD15oFYc5S
https://www.aliyundrive.com/s/MyGribbA3zJ
https://www.aliyundrive.com/s/uY9gb1DpT35
https://www.aliyundrive.com/s/e4b41hvh5G1
https://www.aliyundrive.com/s/1oqiUQDTGXm
https://www.aliyundrive.com/s/Ph1kmJi8YMD
https://www.aliyundrive.com/s/Ud8ksDZK7cL
https://www.aliyundrive.com/s/4fBne5vZWs7
https://www.aliyundrive.com/s/ZJWM15RMb4X
https://www.aliyundrive.com/s/TSJ28iZW8Wu
https://www.aliyundrive.com/s/kPLJaBDzGae
https://www.aliyundrive.com/s/bwhHcDJ4xpQ

**Comment by smloli** [comment]
> > > 好像最新版不再导出名件名，并且有的链接是有效的也会判定为无效链接
> > 
> > 
> > 可以发一份测试时的链接吗
> 
> 作者竟然还维护啊！有点小意外。我再测测百度的https://www.aliyundrive.com/s/bwhHcDJ4xpQ https://www.aliyundrive.com/s/aK8b4rFPuVi https://www.aliyundrive.com/s/gKT6MDE4fv1 https://www.aliyundrive.com/s/wRscEFhYTyv https://www.aliyundrive.com/s/2VszP64VL6q https://www.aliyundrive.com/s/5Q1WzBUaAKb https://www.aliyundrive.com/s/sqEnbkR41qB https://www.aliyundrive.com/s/EhwyeYXouk6 https://www.aliyundrive.com/s/BDSEnik5Efr https://www.aliyundrive.com/s/bWoQqgCDDEZ https://www.aliyundrive.com/s/ywQR3hvgh9e https://www.aliyundrive.com/s/vK9eJMjRszu https://www.aliyundrive.com/s/vmD15oFYc5S https://www.aliyundrive.com/s/MyGribbA3zJ https://www.aliyundrive.com/s/uY9gb1DpT35 https://www.aliyundrive.com/s/e4b41hvh5G1 https://www.aliyundrive.com/s/1oqiUQDTGXm https://www.aliyundrive.com/s/Ph1kmJi8YMD https://www.aliyundrive.com/s/Ud8ksDZK7cL https://www.aliyundrive.com/s/4fBne5vZWs7 https://www.aliyundrive.com/s/ZJWM15RMb4X https://www.aliyundrive.com/s/TSJ28iZW8Wu https://www.aliyundrive.com/s/kPLJaBDzGae https://www.aliyundrive.com/s/bwhHcDJ4xpQ

已经修复了，可以下载最新版重新测试一下
