### ISSUE TITLE
我又来了！部分链接其实是有效的需要多次刷新才能正确显示。

### ISSUE THREAD

**Issue by yunskyline** [smloli/panCheckUrl#8]
有的链接检测到是失效链接，打开时会提示链接错误，但刷新后几次又能正常打开。
刚开始我以为是检测太多太频繁导致，暂停了几天，再次测试失效的链接，还是一样报失效，多次刷新又能打开链接，检测没有检测过的内容则部分能正确检测出失效与否。
![image](https://github.com/smloli/panCheckUrl/assets/47986399/ace64071-56b6-4a9e-8a65-fe8ebfbe68ee)
![image](https://github.com/smloli/panCheckUrl/assets/47986399/ffa518d6-bc11-427f-ace3-451c35a45767)
![image](https://github.com/smloli/panCheckUrl/assets/47986399/5e1d480f-a022-40f1-8c41-74b078dd25bc)
附上测试内容

http://www.aliyundrive.com/s/qLVgamB72nu
http://www.aliyundrive.com/s/qLwR8bgjXNV
http://www.aliyundrive.com/s/QLXFay5ddJf
http://www.aliyundrive.com/s/qLxGqCwfe18
http://www.aliyundrive.com/s/qLxtpshvsN9
http://www.aliyundrive.com/s/QLyA4fqsooX
http://www.aliyundrive.com/s/QLZ889Kwo3y
http://www.aliyundrive.com/s/qLzFUanG3Yx
http://www.aliyundrive.com/s/QLZGhK49d4E
http://www.aliyundrive.com/s/QLZGReGYQej
http://www.aliyundrive.com/s/QLZV5UHifzE
http://www.aliyundrive.com/s/Qm184EPuscg
http://www.aliyundrive.com/s/QM1Nc7t85St
http://www.aliyundrive.com/s/qM1U3yTwuqr
http://www.aliyundrive.com/s/QM1uzF48YS7
http://www.aliyundrive.com/s/qm1XYwXsUWP
http://www.aliyundrive.com/s/qm24APFZiAp
http://www.aliyundrive.com/s/Qm2ACTB5aL2
http://www.aliyundrive.com/s/QM2CJRw7zUY
http://www.aliyundrive.com/s/Qm2KPjJjaob
http://www.aliyundrive.com/s/QM2NdBb7TVc
http://www.aliyundrive.com/s/QM2TQKFKra5
http://www.aliyundrive.com/s/Qm2VKziJX5f
http://www.aliyundrive.com/s/QM3BXP2Fqve
http://www.aliyundrive.com/s/Qm3NaArkvrF
http://www.aliyundrive.com/s/QM3uZVPdwBU
http://www.aliyundrive.com/s/qm425hVCVYL
http://www.aliyundrive.com/s/QM4aN99eMVV
http://www.aliyundrive.com/s/Qm4aU7Lh1fn
http://www.aliyundrive.com/s/qm4ibghGv1T
http://www.aliyundrive.com/s/Qm4skq7h22s
http://www.aliyundrive.com/s/QM5A3jt9hmc
http://www.aliyundrive.com/s/qm5EXWq5dXi
http://www.aliyundrive.com/s/Qm5WDJVy6bL
http://www.aliyundrive.com/s/Qm68hPs2sNv
http://www.aliyundrive.com/s/qm74gdQgvvE
http://www.aliyundrive.com/s/qM7mfgAXFRR
http://www.aliyundrive.com/s/Qm8pwCwfxtG
http://www.aliyundrive.com/s/QM8RgkQDtoj
http://www.aliyundrive.com/s/qM9aFsonDEV
http://www.aliyundrive.com/s/qMAeAomQSkm
http://www.aliyundrive.com/s/QMAfDatMLEL
http://www.aliyundrive.com/s/QmagJbQctwp
http://www.aliyundrive.com/s/QMaij7VTvdX
http://www.aliyundrive.com/s/qmauxtdJCaz
http://www.aliyundrive.com/s/qmAvaNbBTkz
http://www.aliyundrive.com/s/qMazN67hwtp
http://www.aliyundrive.com/s/qmAzvsjFQdm
http://www.aliyundrive.com/s/qMB1prprCGa
http://www.aliyundrive.com/s/qmB2bHNk2Ui
http://www.aliyundrive.com/s/QMbASzkRvP2
http://www.aliyundrive.com/s/qMbJmb2SkDK
http://www.aliyundrive.com/s/qmBKrhq6St4
http://www.aliyundrive.com/s/qmBt3uRZ88w
http://www.aliyundrive.com/s/QMcApg9kMJx
http://www.aliyundrive.com/s/QMCDzELZexF
http://www.aliyundrive.com/s/qMcE1H8XCFD
http://www.aliyundrive.com/s/QmCf1FMoHLU
http://www.aliyundrive.com/s/qMCr7LX3ZVA
http://www.aliyundrive.com/s/QMd4KChj9Fh
http://www.aliyundrive.com/s/qmd66F6Zaay
http://www.aliyundrive.com/s/QmdC6ZPqVTc
http://www.aliyundrive.com/s/qmDECKJ5TUk

**Comment by smloli** [comment]
> 有的链接检测到是失效链接，打开时会提示链接错误，但刷新后几次又能正常打开。 刚开始我以为是检测太多太频繁导致，暂停了几天，再次测试失效的链接，还是一样报失效，多次刷新又能打开链接，检测没有检测过的内容则部分能正确检测出失效与否。 ![image](https://private-user-images.githubusercontent.com/47986399/293086581-ace64071-56b6-4a9e-8a65-fe8ebfbe68ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwODY4MDUsIm5iZiI6MTcwNDA4NjUwNSwicGF0aCI6Ii80Nzk4NjM5OS8yOTMwODY1ODEtYWNlNjQwNzEtNTZiNi00YTllLThhNjUtZmU4ZWJmYmU2OGVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDA1MjE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjZDM3MjhkNGIwMTQ2ZTdkODkyNDU1MzgzMjBiMjQzOWQ2OGFmOGEzZGE0ZWJmZjRhOTBjNjBjZDJkMDhkYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g-hoeOyD1jk3ZKSc4FUuqkkEhiEvvrQI0_z6CTcCtD0) ![image](https://private-user-images.githubusercontent.com/47986399/293086653-ffa518d6-bc11-427f-ace3-451c35a45767.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwODY4MDUsIm5iZiI6MTcwNDA4NjUwNSwicGF0aCI6Ii80Nzk4NjM5OS8yOTMwODY2NTMtZmZhNTE4ZDYtYmMxMS00MjdmLWFjZTMtNDUxYzM1YTQ1NzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDA1MjE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhOTgzYTg1NmFkNDA5NjgwMjFkODFlYjZlMDMyY2E3ZmI4NTZmMGZmYzA2MWNkNDJhYzdmNjc5YjkxNTNhNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DmPyldpAwsQUNknICYZXlS0hxeI9SspDTmYbiBY-WGg) ![image](https://private-user-images.githubusercontent.com/47986399/293086744-5e1d480f-a022-40f1-8c41-74b078dd25bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwODY4MDUsIm5iZiI6MTcwNDA4NjUwNSwicGF0aCI6Ii80Nzk4NjM5OS8yOTMwODY3NDQtNWUxZDQ4MGYtYTAyMi00MGYxLThjNDEtNzRiMDc4ZGQyNWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDA1MjE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhYTRiYjk4OWIwMGQ4NjI5NWQ3MDU3MjM0Zjk2NzgxOGMxNzFjOWFjOGE1Yzk2OTkzYjViNDViOTE1OWRmMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w0Ov4yhXAe83LZGruhQD2dxtHG3EGSvdjYsM2S5z20w) 附上测试内容
> 
> http://www.aliyundrive.com/s/qLVgamB72nu http://www.aliyundrive.com/s/qLwR8bgjXNV http://www.aliyundrive.com/s/QLXFay5ddJf http://www.aliyundrive.com/s/qLxGqCwfe18 http://www.aliyundrive.com/s/qLxtpshvsN9 http://www.aliyundrive.com/s/QLyA4fqsooX http://www.aliyundrive.com/s/QLZ889Kwo3y http://www.aliyundrive.com/s/qLzFUanG3Yx http://www.aliyundrive.com/s/QLZGhK49d4E http://www.aliyundrive.com/s/QLZGReGYQej http://www.aliyundrive.com/s/QLZV5UHifzE http://www.aliyundrive.com/s/Qm184EPuscg http://www.aliyundrive.com/s/QM1Nc7t85St http://www.aliyundrive.com/s/qM1U3yTwuqr http://www.aliyundrive.com/s/QM1uzF48YS7 http://www.aliyundrive.com/s/qm1XYwXsUWP http://www.aliyundrive.com/s/qm24APFZiAp http://www.aliyundrive.com/s/Qm2ACTB5aL2 http://www.aliyundrive.com/s/QM2CJRw7zUY http://www.aliyundrive.com/s/Qm2KPjJjaob http://www.aliyundrive.com/s/QM2NdBb7TVc http://www.aliyundrive.com/s/QM2TQKFKra5 http://www.aliyundrive.com/s/Qm2VKziJX5f http://www.aliyundrive.com/s/QM3BXP2Fqve http://www.aliyundrive.com/s/Qm3NaArkvrF http://www.aliyundrive.com/s/QM3uZVPdwBU http://www.aliyundrive.com/s/qm425hVCVYL http://www.aliyundrive.com/s/QM4aN99eMVV http://www.aliyundrive.com/s/Qm4aU7Lh1fn http://www.aliyundrive.com/s/qm4ibghGv1T http://www.aliyundrive.com/s/Qm4skq7h22s http://www.aliyundrive.com/s/QM5A3jt9hmc http://www.aliyundrive.com/s/qm5EXWq5dXi http://www.aliyundrive.com/s/Qm5WDJVy6bL http://www.aliyundrive.com/s/Qm68hPs2sNv http://www.aliyundrive.com/s/qm74gdQgvvE http://www.aliyundrive.com/s/qM7mfgAXFRR http://www.aliyundrive.com/s/Qm8pwCwfxtG http://www.aliyundrive.com/s/QM8RgkQDtoj http://www.aliyundrive.com/s/qM9aFsonDEV http://www.aliyundrive.com/s/qMAeAomQSkm http://www.aliyundrive.com/s/QMAfDatMLEL http://www.aliyundrive.com/s/QmagJbQctwp http://www.aliyundrive.com/s/QMaij7VTvdX http://www.aliyundrive.com/s/qmauxtdJCaz http://www.aliyundrive.com/s/qmAvaNbBTkz http://www.aliyundrive.com/s/qMazN67hwtp http://www.aliyundrive.com/s/qmAzvsjFQdm http://www.aliyundrive.com/s/qMB1prprCGa http://www.aliyundrive.com/s/qmB2bHNk2Ui http://www.aliyundrive.com/s/QMbASzkRvP2 http://www.aliyundrive.com/s/qMbJmb2SkDK http://www.aliyundrive.com/s/qmBKrhq6St4 http://www.aliyundrive.com/s/qmBt3uRZ88w http://www.aliyundrive.com/s/QMcApg9kMJx http://www.aliyundrive.com/s/QMCDzELZexF http://www.aliyundrive.com/s/qMcE1H8XCFD http://www.aliyundrive.com/s/QmCf1FMoHLU http://www.aliyundrive.com/s/qMCr7LX3ZVA http://www.aliyundrive.com/s/QMd4KChj9Fh http://www.aliyundrive.com/s/qmd66F6Zaay http://www.aliyundrive.com/s/QmdC6ZPqVTc http://www.aliyundrive.com/s/qmDECKJ5TUk

现在重新下载最新版本试试
