### ISSUE TITLE
不支持检测阿里云www.alipan.com域名的链接，结果为全部失效，手动替换为www.aliyundrive.com可以正常检测

### ISSUE THREAD

**Issue by hzy132** [smloli/panCheckUrl#9]
这是一个小问题，这里我提issue目的是告诉其他人检测alipan.com失效不是真的失效了

**Comment by smloli** [comment]
> 这是一个小问题，这里我提issue目的是告诉其他人检测alipan.com失效不是真的失效了

已经支持检测了
